Repository poshbotio/PoshBot, pull requests merged in 2018-10, with the labels that each got.

#122 Enable running multiple versions of PoshBot side-by-side
  PoshBot/Classes/Command.ps1
  PoshBot/Public/New-PoshBotScheduledTask.ps1
  PoshBot/Public/Start-PoshBot.ps1
  PoshBot/Task/StartPoshBot.ps1
Labels: enhancement

#111 Remove line breaks issue#109
  PoshBot/Classes/Bot.ps1
Labels: bug, hacktoberfest

#121 Prevent multiple execution of commands scheduled in the past
  PoshBot/Classes/Logger.ps1
  PoshBot/Classes/ScheduledMessage.ps1
  PoshBot/Classes/Scheduler.ps1
  Tests/Unit/Classes/ScheduledMessages.tests.ps1
  Tests/Unit/Classes/Scheduler.tests.ps1
Labels: bug, hacktoberfest

#129 Use module-qualified cmdlet names when invoking plugins
  PoshBot/Classes/Command.ps1
  PoshBot/Classes/Plugin.ps1
  PoshBot/Classes/PluginManager.ps1
  PoshBot/Plugins/Builtin/Public/Get-CommandHelp.ps1
Labels: enhancement, hacktoberfest
