Repository poshbotio/PoshBot, pull requests merged in 2019-10, with the labels that each got.

#177 updated Discord backend to work with PS 5.1, 6.2.3 and 7
  PoshBot/Implementations/Discord/DiscordBackend.ps1
  PoshBot/Implementations/Discord/DiscordConnection.ps1
  PoshBot/Implementations/Slack/SlackConnection.ps1
  build.ps1
  docs/guides/backends/discord-add-bot-name.png
  docs/guides/backends/discord-add-bot.png
  docs/guides/backends/discord-new-application.png
  docs/guides/backends/setup-discord-backend.md
  docs/reference/functions/Get-PoshBotStatefulData.md
  docs/reference/functions/New-PoshBotDiscordBackend.md
  docs/reference/functions/New-PoshBotFileUpload.md
  docs/reference/functions/New-PoshBotMiddlewareHook.md
  docs/reference/functions/New-PoshBotTeamsBackend.md
  docs/reference/functions/PoshBot.md
  docs/reference/functions/Remove-PoshBotStatefulData.md
  docs/reference/functions/Set-PoshBotStatefulData.md
  docs/reference/functions/get-poshbot.md
  docs/reference/functions/get-poshbotconfiguration.md
  docs/reference/functions/new-poshbotcardresponse.md
  docs/reference/functions/new-poshbotconfiguration.md
  docs/reference/functions/new-poshbotinstance.md
  docs/reference/functions/new-poshbotscheduledtask.md
  docs/reference/functions/new-poshbotslackbackend.md
  docs/reference/functions/new-poshbottextresponse.md
  docs/reference/functions/save-poshbotconfiguration.md
  docs/reference/functions/start-poshbot.md
  docs/reference/functions/stop-poshbot.md
  mkdocs.yml
Labels: backend, hacktoberfest

#178 Add additional objects to !slap
  PoshBot/Plugins/Builtin/Public/Slap.ps1
  docs/reference/commands/Slap.md
Labels: enhancement, hacktoberfest

#185 Updated docs to remove setting runtime ~1
  docs/guides/backends/app-studio-edit-bot-manifest.png
  docs/guides/backends/setup-teams-backend.md
Labels: documentation, hacktoberfest
